id: I9FACEC7A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T17:55:31+00:00'
last_modified: '2022-06-07T15:17:00.306370+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18658
  title: རྩོམ་རིག་གཞུང་ལུགས་གནད་བསྡུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    A57B:
      image_group_id: I8LS18660
      title: ''
      total_pages: 605
      order: 1
      base_file: A57B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
