id: P001824
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18658
  title: རྩོམ་རིག་གཞུང་ལུགས་གནད་བསྡུས།
  author: ''
  volumes:
    fda1a9fe9c4348fda2ae39c61a56f113:
      image_group_id: I8LS18660
      title: ''
      volume_number: 1
      total_pages: 605
      base_file: v001.txt
