id: P001824
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-17 10:23:44.401286
source_metadata:
  id: bdr:W8LS18658
  title: རྩོམ་རིག་གཞུང་ལུགས་གནད་བསྡུས།
  author: ''
  volumes:
    fda1a9fe9c4348fda2ae39c61a56f113:
      image_group_id: I8LS18660
      title: ''
      volume_number: 1
      total_pages: 605
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
